### ISSUE TITLE
Script is deleted

### ISSUE THREAD

**Issue by DRehman-Bilal** [maximedrn/hcaptcha-solver-python-selenium#11]
when i opened link for the script it says the script has been disabled idk if its error popping up for me only but yesterday i have opened same script and it was working

**Comment by DRehman-Bilal** [comment]
luckily i have saved that script in tampermonkey so yea i have that and i made same thing

**Comment by DRehman-Bilal** [comment]
I shall be thankful if you help me with it it installs script open the website but donot solve captcha

**Comment by EmWillWei** [comment]
> luckily i have saved that script in tampermonkey so yea i have that and i made same thing

Could you please share that script, I just see this repo and find the script was deleted yesterday.

**Comment by DRehman-Bilal** [comment]
> > luckily i have saved that script in tampermonkey so yea i have that and i made same thing
> 
> Could you please share that script, I just see this repo and find the script was deleted yesterday.

sure search that again and u will find a script with author name AbdulRehman Sheikh

**Comment by maximedrn** [comment]
I changed the URL in the main.py. Now it should download the script.

**Comment by DRehman-Bilal** [comment]
> I changed the URL in the main.py. Now it should download the script.

can u tell why its not solving it? is there error in script

**Comment by Jarvn** [comment]
Not solving for me either

**Comment by maximedrn** [comment]
I uploaded the original script to my GreasyFork account as private, so it can only be accessed from the URL, not the website. I changed a lot of things for this tool (Geckodriver support, headless mode support, you can delete comments in the command prompt, etc).
This tool should now work as before.
