### ISSUE TITLE
How to use the Undetectable ChromeDriver?

### ISSUE THREAD

**Issue by mkbdes** [maximedrn/hcaptcha-solver-python-selenium#13]
is it possible to add undetect chromedriver?

**Comment by maximedrn** [comment]
Yes, you can add the Undectable ChromeDriver.
You just have to edit this [function](https://github.com/maximedrn/hcaptcha-solver-python-selenium/blob/44b242c1fbc5a8920c8536837db8603811bc9a26/app/hcaptcha.py#L63).
