### ISSUE TITLE
Headless Ubuntu Server support

### ISSUE THREAD

**Issue by darvd29** [maximedrn/hcaptcha-solver-python-selenium#3]
Hello,
Is there a way to get this working on headless Ubuntu Server? I installed google chrome, downloaded corresponding chromedriver and changed the path in main.py. If I leave the line  `# options.add_argument("headless")  # Headless ChromeDriver` commented out then it says that Chrome has crashed, and if I remove the # then it says `
selenium.common.exceptions.WebDriverException: Message: unknown error: failed to wait for extension background page to load: chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.html
from unknown error: page could not be found: chrome-extension://dhdgffkkebhmkfjojejmpbldmpobfkfo/background.html
`

**Comment by maximedrn** [comment]
Hi, no you can't. The chromedriver doesn't support headless mode while using an extension. You can try with a geckodriver (Firefox), you have to change the CRX extension with a XPI.
