### ISSUE TITLE
Could I use the hcaptcha test site you built?

### ISSUE THREAD

**Issue by QIN2DIM** [maximedrn/hcaptcha-solver-python-selenium#8]
Hi, I used the `hcaptcha` test site you built in the [hcaptcha-challenger](https://github.com/QIN2DIM/hcaptcha-challenger) project I created recently.

In addition, I noticed that the performance issues were mentioned in the previous discussion of this extension.
- https://github.com/maximedrn/hcaptcha-solver-python-selenium/issues/1
- https://github.com/maximedrn/hcaptcha-solver-python-selenium/issues/3

Coincidentally, all these problems are solved in `hcaptcha-challenger`.🤷‍♀️
- The recognition task is done independently and not with the help of extensions, so the browser can be started **headless**.
- The recognition module uses a self-trained yolov5n6(onnx) to perform two challenging rounds of the recognition task in one second in extreme cases.This model has **excellent penetration** of the hcaptcha challenge, is less than 15MB in size, and can run on almost any embedded device.

In the following demo, I am using yolov5s6(onnx) with a larger parameter size to start the solution. if you specify yolov5n6(onnx) to start, the detection speed can be twice as fast...🤦‍♂️
![hcaptcha-challenger-demo](https://github.com/QIN2DIM/img_pool/raw/main/img/hcaptcha-challenger2.gif)

**Comment by maximedrn** [comment]
To answer the title `Can I use the hcaptcha test site you built`, yes you can :)
This repository is no longer maintained and, I know, is very slow compared to image recognition (Yolo v5s6).
